### ISSUE TITLE
How to encode negative precission?

### ISSUE THREAD

**Issue by nicklasaven** [TWKB/Specification#9]
In the first "magic byte" the last 4 bits is used for precision. The number indicates how many decimals that is stored. 

Now that number is an unsigned value which means there can not be negative values.

There is a need for negative values to indicate for example 10 m precision in meter based unit.
There is also space for that information. Today we only allow from 0 to 7 decimals which means that 4 bits is enough also for sign information.

Since this will be a breaking change it is important that we do this change soon, before there is more implementeions out there
But how to encode it?

Should it be like in VarInt with zig-zag encoding meaning that the encoded value :
0 means 0
1 means -1
2 means 1
3 means -2 
and so on

...or should it be like the common way with integers (thwo's commplement
http://en.wikipedia.org/wiki/Signed_number_representations
 that the encoded value:
0 means 0
1 means 1
2 means 2
.......
8 means -8
9 means -7
10 means -6
....
15 means -1

...or should we just use a sign bit. That wouldn't be a breaking change from what we have today? Right?

...or something else

**Comment by pramsey** [comment]
Two's complement would be fine.

**Comment by pramsey** [comment]
Does your varint implementation handle negative numbers?

**Comment by nicklasaven** [comment]
Yes it handles signed int

http://trac.osgeo.org/postgis/browser/trunk/liblwgeom/varint.c#L130

But that code expects 64bit input.
Is it enough to cast to 64 bit before sending to function? 
Not sure right now but probably.

**Comment by nicklasaven** [comment]
In new spec precision for X an y is signed by zig-zag encoding. But Z and M precision is unsigned.
